#override defaults for dev
version: "3.3"

services:
  app_server:
    volumes:
      - ~/.npm:/.npm
    environment:
      CONTAINER_UID: 33
      APPLICATION_UID: 33
      APPLICATION_GID: 33
    ports:
      - "${APP_PORT_8000}:8000"
      - "${APP_PORT_8080}:8080"
      - "${APP_PORT_8005}:8005"
      - "${APP_PORT_9999}:9999"

  app_mysql:
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/mysql-data

  adminer:
    ports:
      - "${ADMINER_PORT}:8080"

  mailhog:
    ports:
      - "${MAILHOG_PORT}:8025"

  elasticsearch:
    ports:
      - "${ELASTIC_PORT_9200}:9200"
      - "${ELASTIC_PORT_9300}:9300"
